# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rea Guiloreza
email: reaguiloreza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rea.website" # the base hostname & protocol for your site
twitter_username: rearidinghood
github_username:  eyafaer

# Build settings
markdown: kramdown
